name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install Dependencies
      run: |
        cd frontend
        npm ci
        
    - name: Build
      run: |
        cd frontend
        npm run build
      env:
        CI: false
        REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
        
    - name: Test
      run: |
        cd frontend
        npm test -- --passWithNoTests
        
    - name: Cache build
      uses: actions/cache@v3
      with:
        path: frontend/build
        key: ${{ runner.os }}-build-${{ github.sha }}

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Restore cached build
      uses: actions/cache@v3
      with:
        path: frontend/build
        key: ${{ runner.os }}-build-${{ github.sha }}
    
    - name: Configure custom domain
      run: echo "datdrinkdessert.com" > frontend/build/CNAME
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: frontend/build
        branch: gh-pages 